#!/bin/sh
git secrets --pre_commit_hook -- "$@"

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
staged_target=$(git diff --cached --diff-filter=d --name-only | grep --line-regexp 'README.md')
[ -z "$staged_target" ] && exit 0
npm run lint
exit_code=$?
if [ $exit_code -ne 0 ]
then
  echo "${RED} ❌ Lint errors have occurred. Try 'npm run fix-lint'${NC}"
  exit 1
else
  echo "${GREEN} ✔ Lint did not find any errors${NC}"
  exit 0
fi